stages:
  - dependencies
  - haproxy

variables:
  TZ: "UTC"
  GIT_DEPTH: "1"

.build-job: &build-job
  image: docker.io/library/debian:bullseye
  needs: [ ]
  before_script:
    - apt -qq update
    - apt install -y --no-install-recommends -qq build-essential ca-certificates curl tar

lua:
  <<: *build-job
  stage: dependencies
  script:
    - apt -qq update && apt install -qq -y --no-install-recommends libreadline-dev
    - make -C deps/lua
  artifacts:
    expire_in: 14 days
    paths: [ "deps/lua/dist" ]

pcre2:
  <<: *build-job
  stage: dependencies
  script:
    - apt -qq update && apt install -qq -y --no-install-recommends cmake
    - make -C deps/pcre2
  artifacts:
    expire_in: 14 days
    paths: [ "deps/pcre2/dist" ]

quictls:
  <<: *build-job
  stage: dependencies
  script: make -C deps/quictls
  artifacts:
    expire_in: 14 days
    paths: [ "deps/quictls/dist", "quictls-*-dist.tar.gz" ]

haproxy:
  <<: *build-job
  stage: haproxy
  script:
    - apt -qq update && apt install -qq -y --no-install-recommends git libsystemd-dev
    - make -C haproxy
  needs:
    - job: lua
      artifacts: true
    - job: pcre2
      artifacts: true
    - job: quictls
      artifacts: true
  artifacts:
    expire_in: 14 days
    paths: [ "haproxy/dist" ]
