name: Fetch HAProxy dependencies
description: "Retrieve previously compiled build-time dependencies"

inputs:
  INSTALL_NATIVE_DEPS:
    description: Install native build dependencies
    required: false
    default: "true"

runs:
  using: "composite"

  steps:
    - name: Dependencies - Fetch - LUA
      uses: actions/download-artifact@v3
      with:
        name: lua-dist.tar.gz
        path: deps/lua
    - name: Dependencies - Unpack - LUA
      shell: bash
      run: |
        mkdir -pv deps/lua/dist
        tar -C deps/lua/dist -xf deps/lua/lua-dist.tar.gz

    - name: Dependencies - Fetch - PCRE2
      uses: actions/download-artifact@v3
      with:
        name: pcre2-dist.tar.gz
        path: deps/pcre2
    - name: Dependencies - Unpack - PCRE2
      shell: bash
      run: |
        mkdir -pv deps/pcre2/dist
        tar -C deps/pcre2/dist -xf deps/pcre2/pcre2-dist.tar.gz

    - name: Dependencies - Fetch - QuicTLS
      uses: actions/download-artifact@v3
      with:
        name: quictls-dist.tar.gz
        path: deps/quictls
    - name: Dependencies - Unpack - QuicTLS
      shell: bash
      run: |
        mkdir -pv deps/quictls/dist
        tar -C deps/quictls/dist -xf deps/quictls/quictls-dist.tar.gz

    - name: Dependencies - Fetch - VTest
      uses: actions/download-artifact@v3
      with:
        name: vtest-dist.tar.gz
        path: deps/vtest
    - name: Dependencies - Unpack - VTest
      shell: bash
      run: |
        mkdir -pv deps/vtest/dist
        tar -C deps/vtest/dist -xf deps/vtest/vtest-dist.tar.gz

    - name: Install native build dependencies
      if: ${{ inputs.INSTALL_NATIVE_DEPS == 'true' }}
      shell: bash
      run: |
        apt update && apt install -y \
          bzip2 \
          devscripts \
          debhelper \
          pkg-config \
          libpcre2-dev \
          libreadline-dev \
          libsystemd-dev \
          zlib1g-dev
