name: Setup LLVM and Clang
description: |
  Install, with caching, the LLVM and Clang toolkits

  - because fuck defaulting to old-ass GCC
  - and especially shit like https://github.com/vtest/VTest/issues/12

runs:
  using: "composite"
  steps:
    - name: Cache LLVM and Clang
      id: cache-llvm-clang
      uses: actions/cache@v3
      with:
        path: |
          ./llvm
        key: llvm-14
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14"
        cached: ${{ steps.cache-llvm-clang.outputs.cache-hit }}
