on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 17

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 17
      HAPROXY_FLAVOUR: "stable"
      # https://git.haproxy.org/?p=haproxy-2.9.git;a=commit;h=v2.9.5
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-2.9.git"
      HAPROXY_VERSION: "2.9-stable"
      HAPROXY_GITREF: "v2.9.5"
      HAPROXY_DATAPLANEAPI_VERSION: "v2.9"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 17
      HAPROXY_FLAVOUR: "dev"
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=dec017575d3a18c92e0d112bc8b92e1c557a10b8
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "3.0-dev"
      HAPROXY_GITREF: "dec017575d3a18c92e0d112bc8b92e1c557a10b8"
      HAPROXY_DATAPLANEAPI_VERSION: "master"
