on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  schedule:
    - cron: "0 10 * * 1"

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      CLANG_VERSION: 14

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      CLANG_VERSION: 14
      # https://git.haproxy.org/?p=haproxy-2.7.git;a=commit;h=4dadaaafb20106619510fd3fc6f2819f47777729
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-2.7.git"
      HAPROXY_VERSION: "2.7-stable"
      HAPROXY_GITREF: "4dadaaafb20106619510fd3fc6f2819f47777729"
      BUILD_PATCHES_DIR: "patches-stable"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      CLANG_VERSION: 14
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=7d6270a84554283557c2707d6df2c275e81c8bf1
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "2.8-dev"
      HAPROXY_GITREF: "7d6270a84554283557c2707d6df2c275e81c8bf1"
      BUILD_PATCHES_DIR: "patches-dev"
