on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14
      HAPROXY_FLAVOUR: "stable"
      # https://git.haproxy.org/?p=haproxy-2.8.git;a=commit;h=fdd8154ed37fef7f351075caa357917f94704dd7
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-2.8.git"
      HAPROXY_VERSION: "2.8-stable"
      HAPROXY_GITREF: "fdd8154ed37fef7f351075caa357917f94704dd7"
      HAPROXY_DATAPLANEAPI_VERSION: "v2.7"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14
      HAPROXY_FLAVOUR: "dev"
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=c8bb9aeb07bfae0b7cf421611fdddcb924508adc
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "2.8-dev"
      HAPROXY_GITREF: "c8bb9aeb07bfae0b7cf421611fdddcb924508adc"
      HAPROXY_DATAPLANEAPI_VERSION: "master"
