on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14
      HAPROXY_FLAVOUR: "stable"
      # https://git.haproxy.org/?p=haproxy-2.8.git;a=commit;h=v2.8.1
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-2.8.git"
      HAPROXY_VERSION: "2.8-stable"
      HAPROXY_GITREF: "v2.8.1"
      HAPROXY_DATAPLANEAPI_VERSION: "v2.8"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14
      HAPROXY_FLAVOUR: "dev"
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=f7dcceccc9a82189b233a16fd017d16a5d17c594
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "2.9-dev"
      HAPROXY_GITREF: "f7dcceccc9a82189b233a16fd017d16a5d17c594"
      HAPROXY_DATAPLANEAPI_VERSION: "master"
