on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 16

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 16
      HAPROXY_FLAVOUR: "stable"
      # https://git.haproxy.org/?p=haproxy-2.9.git;a=commit;h=v2.9.1
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-2.9.git"
      HAPROXY_VERSION: "2.9-stable"
      HAPROXY_GITREF: "v2.9.1"
      HAPROXY_DATAPLANEAPI_VERSION: "v2.9.0"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 16
      HAPROXY_FLAVOUR: "dev"
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=c3a94a3750e473dc5a5402dfd9332d1c044d049e
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "3.0-dev"
      HAPROXY_GITREF: "c3a94a3750e473dc5a5402dfd9332d1c044d049e"
      HAPROXY_DATAPLANEAPI_VERSION: "master"
