on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 16

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 16
      HAPROXY_FLAVOUR: "stable"
      # https://git.haproxy.org/?p=haproxy-2.9.git;a=commit;h=v2.9.0
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-2.9.git"
      HAPROXY_VERSION: "2.9-stable"
      HAPROXY_GITREF: "v2.9.0"
      HAPROXY_DATAPLANEAPI_VERSION: "v2.9.0"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      CLANG_VERSION: 16
      HAPROXY_FLAVOUR: "dev"
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=f8e095b05828b8c82a01e37a18ea33e581e55431
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "2.9-dev"
      HAPROXY_GITREF: "f8e095b05828b8c82a01e37a18ea33e581e55431"
      HAPROXY_DATAPLANEAPI_VERSION: "master"
