on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14
      HAPROXY_FLAVOUR: "stable"
      # https://git.haproxy.org/?p=haproxy-2.7.git;a=commit;h=feedf1414f1a9522f5d37dc080d5b3bd9b88627d
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-2.7.git"
      HAPROXY_VERSION: "2.7-stable"
      HAPROXY_GITREF: "feedf1414f1a9522f5d37dc080d5b3bd9b88627d"
      HAPROXY_DATAPLANEAPI_VERSION: "v2.7"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bullseye"
      CLANG_VERSION: 14
      HAPROXY_FLAVOUR: "dev"
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=ffdf6a32a7413d5bcf9223c3556b765b5e456a69
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "2.8-dev"
      HAPROXY_GITREF: "ffdf6a32a7413d5bcf9223c3556b765b5e456a69"
      HAPROXY_DATAPLANEAPI_VERSION: "master"
