on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  haproxy-dependencies:
    uses: "./.github/workflows/haproxy-deps.yml"
    with:
      DEBIAN_CODENAME: "bookworm"

  dist-stable:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      HAPROXY_FLAVOUR: "stable"
      # https://git.haproxy.org/?p=haproxy-3.0.git;a=commit;h=v3.0.5
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy-3.0.git"
      HAPROXY_VERSION: "3.0-stable"
      HAPROXY_GITREF: "v3.0.5"
      HAPROXY_DATAPLANEAPI_VERSION: "v2.9"

  dist-dev:
    needs: [ "haproxy-dependencies" ]
    uses: "./.github/workflows/haproxy-dist.yml"
    secrets: "inherit" # for Docker image publication
    with:
      DEBIAN_CODENAME: "bookworm"
      HAPROXY_FLAVOUR: "dev"
      # https://git.haproxy.org/?p=haproxy.git;a=commit;h=dee3f4b3ffabcfd10e9d30adbc25a55e265777f9
      HAPROXY_GITREPO: "https://git.haproxy.org/?p=haproxy.git"
      HAPROXY_VERSION: "3.1-dev"
      HAPROXY_GITREF: "dee3f4b3ffabcfd10e9d30adbc25a55e265777f9"
      HAPROXY_DATAPLANEAPI_VERSION: "master"
