name: Build HAProxy version

on:
  workflow_call:
    inputs:
      CLANG_VERSION:
        required: true
        type: number
      HAPROXY_GITREPO:
        required: true
        type: string
      HAPROXY_VERSION:
        required: true
        type: string
      HAPROXY_GITREF:
        required: true
        type: string
      BUILD_PATCHES_DIR:
        required: true
        type: string

# For Docker publication
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dependencies - Fetch - LUA
        uses: actions/download-artifact@v3
        with:
          name: lua-dist.tar.gz
          path: deps/lua
      - name: Dependencies - Unpack - LUA
        run: |
          mkdir -pv deps/lua/dist
          tar -C deps/lua/dist -xf deps/lua/lua-dist.tar.gz

      - name: Dependencies - Fetch - PCRE2
        uses: actions/download-artifact@v3
        with:
          name: pcre2-dist.tar.gz
          path: deps/pcre2
      - name: Dependencies - Unpack - PCRE2
        run: |
          mkdir -pv deps/pcre2/dist
          tar -C deps/pcre2/dist -xf deps/pcre2/pcre2-dist.tar.gz

      - name: Dependencies - Fetch - QuicTLS
        uses: actions/download-artifact@v3
        with:
          name: quictls-dist.tar.gz
          path: deps/quictls
      - name: Dependencies - Unpack - QuicTLS
        run: |
          mkdir -pv deps/quictls/dist
          tar -C deps/quictls/dist -xf deps/quictls/quictls-dist.tar.gz

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: "${{ inputs.CLANG_VERSION }}"

      - name: Build HAProxy
        run: |
          make -C haproxy \
            HAPROXY_GITREPO="${{ inputs.HAPROXY_GITREPO }}" \
            HAPROXY_VERSION="${{ inputs.HAPROXY_VERSION }}" \
            HAPROXY_GITREF="${{ inputs.HAPROXY_GITREF }}" \
            BUILD_PATCHES_DIR="${{ inputs.BUILD_PATCHES_DIR }}"
      - name: Archive HAProxy Tarball
        uses: actions/upload-artifact@v3
        with:
          name: haproxy-dist.tar.gz
          path: haproxy/haproxy-dist.tar.gz
