name: HAProxy dependencies

on:
  workflow_call:
    inputs:
      DEBIAN_CODENAME:
        required: true
        type: string
      CLANG_VERSION:
        required: true
        type: number

jobs:
  dependency:
    runs-on: ubuntu-latest
    container: "docker.io/library/debian:${{ inputs.DEBIAN_CODENAME }}"
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        dependency_name:
          - lua
          - pcre2
          - quictls
          - vtest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup OS
        uses: "./.github/actions/setup-os"
      #- name: Set up Clang
      #  uses: "./.github/actions/setup-clang"
      - name: Build ${{ matrix.dependency_name }}
        run: make -C deps/${{ matrix.dependency_name }}
      - name: Archive ${{ matrix.dependency_name }} distribution
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.dependency_name }}-dist.tar.gz
          path: deps/${{ matrix.dependency_name }}/${{ matrix.dependency_name }}-dist.tar.gz
