name: Build HAProxy version

on:
  workflow_call:
    inputs:
      DEBIAN_CODENAME:
        required: true
        type: string
      CLANG_VERSION:
        required: true
        type: number
      HAPROXY_FLAVOUR:
        required: true
        type: string
      HAPROXY_GITREPO:
        required: true
        type: string
      HAPROXY_VERSION:
        required: true
        type: string
      HAPROXY_GITREF:
        required: true
        type: string

# For Docker publication
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  regtests:
    runs-on: ubuntu-latest
    container: "docker.io/library/debian:${{ inputs.DEBIAN_CODENAME }}"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup OS
        uses: "./.github/actions/setup-os"
      - name: Fetch build-time dependencies
        uses: "./.github/actions/fetch-deps"
      - name: Set up Clang
        uses: "./.github/actions/setup-clang"
      - name: Build and test
        continue-on-error: true
        run: |
          make -C haproxy \
            HAPROXY_GITREPO="${{ inputs.HAPROXY_GITREPO }}" \
            HAPROXY_VERSION="${{ inputs.HAPROXY_VERSION }}" \
            HAPROXY_GITREF="${{ inputs.HAPROXY_GITREF }}" \
            BUILD_PATCHES_DIR="patches-${{ inputs.HAPROXY_FLAVOUR }}" \
            build test

  dist-binary:
    runs-on: ubuntu-latest
    container: "docker.io/library/debian:${{ inputs.DEBIAN_CODENAME }}"
    permissions:
      contents: read
      packages: write
    needs: [ regtests ]
    strategy:
      matrix:
        dist_type: [ bin, deb ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup OS
        uses: "./.github/actions/setup-os"
      - name: Fetch build-time dependencies
        uses: "./.github/actions/fetch-deps"
      - name: Set up Clang
        uses: "./.github/actions/setup-clang"
      - name: Build distribution
        env:
          BUILD_MESSAGE: "${{ github.event.head_commit.message }}"
        run: |
          make -C haproxy \
            HAPROXY_GITREPO="${{ inputs.HAPROXY_GITREPO }}" \
            HAPROXY_VERSION="${{ inputs.HAPROXY_VERSION }}" \
            HAPROXY_GITREF="${{ inputs.HAPROXY_GITREF }}" \
            BUILD_PATCHES_DIR="patches-${{ inputs.HAPROXY_FLAVOUR }}" \
            dist-${{ matrix.dist_type }}
          ls -l haproxy

      - name: Archive binary tarball
        if: ${{ matrix.dist_type == 'bin' }}
        uses: actions/upload-artifact@v3
        with:
          name: haproxy-${{ inputs.HAPROXY_FLAVOUR }}.tar.gz
          path: haproxy/haproxy-dist.tar.gz

      - name: Collect Debian packages
        if: ${{ matrix.dist_type == 'deb' }}
        run: |
          echo "DEB_BIN=$(ls -1 haproxy/haproxy-dbgsym_*.deb | cut -d'/' -f2)" | tee -a $GITHUB_ENV
          echo "DEB_DBG=$(ls -1 haproxy/haproxy_*.deb | cut -d'/' -f2)" | tee -a $GITHUB_ENV
      - name: Archive Debian packages - binary
        if: ${{ matrix.dist_type == 'deb' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DEB_BIN }}
          path: haproxy/${{ env.DEB_BIN }}
      - name: Archive Debian packages - debug symbols
        if: ${{ matrix.dist_type == 'deb' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DEB_DBG }}
          path: haproxy/${{ env.DEB_DBG }}

  dist-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [ regtests, dist-binary ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch build-time dependencies
        uses: "./.github/actions/fetch-deps"
      - name: Fetch HAProxy dist
        uses: actions/download-artifact@v3
        with:
          name: haproxy-${{ inputs.HAPROXY_FLAVOUR }}.tar.gz
          path: haproxy
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,event=push,enable=true,prefix=branch-{{ branch }}-${{ inputs.HAPROXY_VERSION }}-${{ inputs.HAPROXY_FLAVOUR }}-git-,format=short
            type=sha,event=push,enable={{ is_default_branch }},prefix=${{ inputs.HAPROXY_VERSION }}-${{ inputs.HAPROXY_FLAVOUR }}-git-,format=short
            type=raw,event=push,enable={{ is_default_branch }},value=${{ inputs.HAPROXY_VERSION }}-${{ inputs.HAPROXY_FLAVOUR }}
            type=raw,event=push,enable={{ is_default_branch }},value=${{ inputs.HAPROXY_VERSION }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

