name: HAProxy dependencies

on:
  workflow_call:
    inputs:
      CLANG_VERSION:
        required: true
        type: number

jobs:
  dependency:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        dependency_name:
          - lua
          - pcre2
          - quictls
          - vtest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: "${{ inputs.CLANG_VERSION }}"
      - name: Build ${{ matrix.dependency_name }}
        run: make -C deps/${{ matrix.dependency_name }}
      - name: Archive ${{ matrix.dependency_name }} distribution
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.dependency_name }}-dist.tar.gz
          path: deps/${{ matrix.dependency_name }}/${{ matrix.dependency_name }}-dist.tar.gz
